<?php
/**Generate by ASGENS
*@author virtualspot  
*@date Mon May 06 16:54:08 GMT-04:00 2024  
*@time Mon May 06 16:54:08 GMT-04:00 2024  
*/


namespace App\Models;


use Illuminate\Support\Carbon;

/**
 * Este es la clase modelo para la tabla error_logs.
 *
 * Los siguientes son los campos de la tabla 'error_logs':
 * @property integer $id
 * @property string $description
 * @property string $ip
 * @property string $error
 * @property string $parameters
 * @property string $request
 * @property string $user_id
 * @property Carbon $created_at
 * @property Carbon $updated_at
 * @property string $headers
 * @property string $username
 * @property string $path
 * @property integer $status_code

 * Los siguientes son las relaciones de este modelo :

 **/



class Error_logs extends BaseModel 
{
 /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'error_logs';

   /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'db';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = true;


    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = [];

    /**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Error_logs';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'description',
      'ip',
      'error',
      'parameters',
      'request',
      'user_id',
      'created_at',
      'updated_at',
      'headers',
      'username',
      'path',
      'status_code'
    ];



     /* Many to many relationships */



    protected function rules($scenario = 'create')
    {
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

}


